# This compose file is intended only for local dev usage.
version: "3.4"
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      target: local
    ports:
      - "8022:8000"
    environment:
      - DATASET_FILE_PATH=/datasets/1000_123_final.json
      - USERS_DB_FILE_PATH=/storage/users_db.dat
      - DEBUG=1
      - DEFAULT_PAGE_LIMIT=500
    volumes:
      - ./api/app/:/app/
      - ./datasets/:/datasets/
      - ./api/storage/:/storage/
  datagenerator:
    build:
      context: .
      dockerfile: datagenerator/Dockerfile
      target: local
    environment:
      - DATASETS_DIR=/datasets/
    volumes:
      - ./datagenerator/app/:/app/
      - ./datasets/:/datasets/
  notebook:
    build:
      context: .
      dockerfile: notebook/Dockerfile
    volumes:
      - ./notebook/work:/notebook/work/
