# This compose file is intended only for local dev usage.
version: "3.4"
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      target: local
    ports:
      - "8022:8000"
    environment:
      - DATASETS_DIR=/api/datasets/
    volumes:
      - ./api/app/:/api/app/
      - ./datasets/:/api/datasets/
  datagenerator:
    build:
      context: .
      dockerfile: datagenerator/Dockerfile
      target: local
    environment:
      - DATASETS_DIR=/tx_datagenerator/datasets/
    volumes:
      - ./datagenerator/app/:/datagenerator/app/
      - ./datasets/:/datagenerator/datasets/
  notebook:
    build:
      context: .
      dockerfile: notebook/Dockerfile
    volumes:
      - ./notebook/work:/notebook/work/
